export type ModelRegion = "global" | "china"

export type ModelVendorGroup = {
  id: string
  name: string
  region: ModelRegion
  models: string[]
}

export const MODEL_LIST: ModelVendorGroup[] = [
  {
    id: "openai",
    name: "OpenAI",
    region: "global",
    models: [
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-5.6-luna",
      "gpt-5.5",
      "gpt-5.5-pro",
      "gpt-4.5",
      "gpt-4o",
      "gpt-4-turbo",
      "gpt-4",
      "gpt-3.5-turbo",
      "o1-preview",
      "o1-mini",
      "o3-mini",
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    region: "global",
    models: [
      "claude-fable-5",
      "claude-mythos-5",
      "claude-opus-4.8",
      "claude-opus-4.7",
      "claude-opus-4.1",
      "claude-sonnet-4.5",
      "claude-3.5-sonnet",
      "claude-3-haiku",
      "claude-3-opus",
    ],
  },
  {
    id: "google",
    name: "Google",
    region: "global",
    models: [
      "gemini-3.5-pro",
      "gemini-3.5-flash",
      "gemini-omni-flash",
      "gemini-2.5-pro",
      "gemini-2.0-flash",
      "gemini-2.0-pro",
      "gemini-1.5-pro",
      "gemini-1.5-flash",
      "gemma-2",
      "gemma-7b",
      "gemma-2b",
    ],
  },
  {
    id: "xai",
    name: "xAI",
    region: "global",
    models: ["grok-4.3", "grok-4.2", "grok-4", "grok-3", "grok-2"],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    region: "global",
    models: [
      "mistral-large-2",
      "mistral-large",
      "mistral-7b-v0.3",
      "mistral-7b-v0.2",
      "mistral-7b-v0.1",
      "mixtral-8x7b",
      "mixtral-8x22b",
    ],
  },
  {
    id: "meta",
    name: "Meta (Llama)",
    region: "global",
    models: [
      "llama-4-maverick",
      "llama-3.2-3b",
      "llama-3.2-1b",
      "llama-3.1-8b",
      "llama-3-8b",
      "llama-3-70b",
      "llama-2-7b",
      "llama-2-13b",
      "llama-2-70b",
    ],
  },
  {
    id: "microsoft",
    name: "Microsoft",
    region: "global",
    models: ["phi-4", "phi-3.5", "phi-3-mini", "phi-3-small", "phi-2"],
  },
  {
    id: "deepseek",
    name: "深度求索 (DeepSeek)",
    region: "china",
    models: [
      "deepseek-v4-pro",
      "deepseek-v4-flash",
      "deepseek-v4-pro-max",
      "deepseek-v3.2",
      "deepseek-v3",
      "deepseek-r1",
      "deepseek-r2",
      "deepseek-coder",
    ],
  },
  {
    id: "alibaba",
    name: "阿里巴巴 (通义千问)",
    region: "china",
    models: [
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen-robot-manip",
      "qwen-robot-nav",
      "qwen-robot-world",
      "qwen3-235b-a22b",
      "qwen2.5-7b",
      "qwen2.5-3b",
      "qwen2.5-1.5b",
      "qwen2.5-0.5b",
      "qwen2.5-coder-7b",
    ],
  },
  {
    id: "zhipu",
    name: "智谱AI (GLM)",
    region: "china",
    models: [
      "glm-5.2",
      "glm-5.1",
      "glm-5",
      "glm-5-turbo",
      "glm-4.6v",
      "glm-4.1v-thinking",
      "glm-5v-turbo",
      "glm-ocr",
      "autoglm-phone",
      "glm-4.7",
      "glm-4.6",
      "glm-4",
      "chatglm3-6b",
    ],
  },
  {
    id: "kimi",
    name: "月之暗面 (Kimi)",
    region: "china",
    models: [
      "kimi-k2.7-code",
      "kimi-k2.6",
      "kimi-k2",
      "kimi-k1.5",
      "kimi-vl-a3b-thinking",
    ],
  },
  {
    id: "tencent",
    name: "腾讯 (混元)",
    region: "china",
    models: [
      "hy3-preview",
      "t1-vision",
      "hy-1.8b-2bit",
      "hunyuan-t1-vision",
      "hunyuan",
    ],
  },
  {
    id: "baidu",
    name: "百度 (文心一言)",
    region: "china",
    models: ["wenxin-5.1", "wenxin-5.0", "wenxin-4.5", "wenxin-4"],
  },
  {
    id: "minimax",
    name: "MiniMax",
    region: "china",
    models: ["minimax-m3", "minimax-m2", "minimax-m1", "abab-6.5", "abab-6", "abab-5.5"],
  },
  {
    id: "sensetime",
    name: "商汤科技 (SenseNova)",
    region: "china",
    models: [
      "sensanova-6.7-flash-lite",
      "sensanova-6.7",
      "sensanova-6",
      "sensanova-5",
    ],
  },
  {
    id: "stepfun",
    name: "阶跃星辰 (Step)",
    region: "china",
    models: ["step-3.7-flash", "step-3.5-flash", "step-3", "step-1x-edit"],
  },
  {
    id: "lingyiwanwu",
    name: "零一万物 (Yi)",
    region: "china",
    models: ["yi-lightning", "yi-1.5-34b-chat", "yi-large", "yi-34b", "yi-6b"],
  },
  {
    id: "baichuan",
    name: "百川智能",
    region: "china",
    models: ["baichuan-4", "baichuan-3", "baichuan-2-7b", "baichuan-2-13b"],
  },
  {
    id: "iflytek",
    name: "科大讯飞 (讯飞星火)",
    region: "china",
    models: ["spark-4.0", "spark-3.5", "spark-3", "spark-2"],
  },
]
